SalaCinema/Models/ErrorViewModel.cs
namespace SalaCinema.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SalaCinema/Models/FilmesDto.cs
using System.ComponentModel.DataAnnotations;

namespace SalaCinema.Models
{
    public class FilmesDTo
    {
  
    }
}

SalaCinema/Models/SalaDto.cs
using System.ComponentModel.DataAnnotations;

namespace SalaCinema.Models
{
    public class SalaDto
    {
        //public string Id { get; set; }

        [Display(Name = "Descrição")]
        public string Name { get; set; }
        [Display(Name = "N° Sala")]
        public int NumberRoom { get; set; }
        //public bool Active { get; set; }
    }
}

SalaCinema/Models/ServvidorDto.cs
using System.ComponentModel.DataAnnotations;

namespace SalaCinema.Models
{
    public class ServvidorDto
    {
       
    }
}

SalaCinema/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SalaCinema.Models;
using System.Diagnostics;

namespace SalaCinema.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SalaCinema/Controllers/SalaController.cs
using Microsoft.AspNetCore.Mvc;
using SalaCinema.Models;
using SalaCinema.Service;

namespace SalaCinema.Controllers
{
    public class SalaController : Controller
    {
        private readonly ISalaServiceHttpClient _salaServiceHttpClient;

        public SalaController(ISalaServiceHttpClient salaServiceHttpClient)
        {
            _salaServiceHttpClient = salaServiceHttpClient;
        }

        [HttpGet]
        public IActionResult Index(SalaDto request)
        {
            return View();
        }
        [HttpGet]
        public IActionResult ListarSala()
        {
           List<SalaDto> response = _salaServiceHttpClient.GetSalasAsync().Result;
            return View(response);
        }
   
       public int ContarSala()
        {
            List<SalaDto> response = _salaServiceHttpClient.GetSalasAsync().Result;
            //List<SalaDto> response = (List<SalaDto>)ListarSala();
            var total=response.Count();
            return total;
        }

    }
}

SalaCinema/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Consumindo API</h1>

</div>
<div class="row">

    <!-- Vendas Período -->
    <div class="col-lg-3" id="elemento-1">
        <div class="card mini-stat bg-primary">
            <div class="card-body mini-stat-img">
                <div class="mini-stat-icon">
                    <i class="mdi mdi-currency-usd float-right"></i>
                </div>
                <div class="text-white text-center">

                    <a class="text-white" asp-area="" asp-controller="Sala" asp-action="ListarSala">
                        <h6 class="text-uppercase mb-3">Cadastro de Salas</h6>
                    </a>
                   
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3" id="elemento-2">
        <div class="card mini-stat bg-primary">
            <div class="card-body mini-stat-img">
                <div class="mini-stat-icon">
                    <i class="mdi mdi-tag-text-outline float-right"></i>
                </div>
                <div class="text-white text-center">
                    <a class="text-white" asp-area="" asp-controller="Sala" asp-action="ListarSala">
                        <h6 class="text-uppercase mb-3">Cadastro de Filmes/h6>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3" id="elemento-3">
        <div class="card mini-stat bg-primary">
            <div class="card-body mini-stat-img">
                <div class="mini-stat-icon">
                    <i class="mdi mdi-briefcase-check float-right"></i>
                </div>
                <div class="text-white text-center">

                    <a class="text-white" asp-area="" asp-controller="Sala" asp-action="ListarSala">
                        <h6 class="text-uppercase mb-3">Cadastro de Servidor</h6>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3" id="elemento-4">
        <div class="card mini-stat bg-primary">
            <div class="card-body mini-stat-img">
                <div class="mini-stat-icon">
                    <i class="mdi mdi-tshirt-crew float-right"></i>
                </div>
                <div class="text-white text-center">

                    <a class="text-white" asp-area="" asp-controller="Sala" asp-action="ListarSala">
                        <h6 class="text-uppercase mb-3">Cadastro de Video</h6>
                    </a>
                </div>
            </div>
        </div>
  
  
</div>

<script>
    ContarSala();

        function ContarSala() {
            $.ajax({
                method: 'get',
                dataType: 'json',
                url: '/Sala/ContarSala',
                contentType: 'application/json',
                success: function (retorno) {
                    LoadingContagem('#ValorCard-1', parseFloat(retorno).toFixed(2), 2);
                   
                },
                error: function (err) {
                    console.log(err.responseText);
                }
            });
        }

</script>

SalaCinema/Views/SalaController/Index.cshtml
@model IEnumerable<SalaCinema.Models.SalaDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
          
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberRoom)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberRoom)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

SalaCinema/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SalaCinema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SalaCinema.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SalaCinema</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sala" asp-action="ListarSala">Sala</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - SalaCinema - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>